### PR TITLE
Created ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Apoorva-13**

### CODE REVIEW

**Comment by jhigman** [comment]
Thanks for the PR Apoorva.
I think maybe it has slightly missed the point though - I think the original idea was to use what we already have in the contributor-guide.md as the basis for an issue template, so that a contributor could immediately see the sort of details that are required to add an event or request a change. This one looks more like a straight copy from the hacktoberfest website?

**Comment by Apoorva-13** [comment]
Sorry for this , I can edit it and then  you  can let me if it is apt .

**Comment by Apoorva-13** [comment]
To contribute simply fork and provide a pull request.

## Guidelines to Event descriptions and Titles

1. Link title to the relevant site / Meetup page
2. Keep sentences and paragraphs short and easy to scan
2. Double check your spelling
3. Feel free to include social media links after the title
4. Respect other meetups and the community spirit of what we're trying to achieve as a collaborative, supportive group of organisers. Refrain from any content that is not in keeping with this aim - if further advice is needed raise a comment in your PR
5. If your event uses meetup or tito - include details in the PR and your listings will get pulled from there or make a separate PR on [https://github.com/pavlakis/notts-digital/blob/master/app/configs/groups.php]: the api groups configuration
6. Ensure your meetup is in Nottingham or the immediate area.

## Guidelines to code / markup 

1. Commits must be accompanied by meaningful commit messages

2. PRs that include bug fixing should be accompanied by a step-by-step description of how to reproduce the bug.

**Comment by jhigman** [comment]
@jamietanna how does this look to you, does it do what you hoped?

**Pull request merged**
