### PR TITLE
Added Cyber Security Nottingham

### PR DESCRIPTION
**Pull request by crossowl**
Looks like atom has cleaned ups some white space also, let me know if that's a problem

### CODE REVIEW

**Comment by sdh100shaun** [comment]
thanks for adding this

**Comment by crossowl** [comment]
Thanks Shaun

**Comment by sdh100shaun** [comment]
forgot to say for adding this , to get the event date automatically pulled from meetup add a PR to https://github.com/pavlakis/notts-digital or let us know and we will do that

**Comment by crossowl** [comment]
> forgot to say for adding this...
I'm already on it ;) cheers

**Comment by crossowl** [comment]
https://github.com/pavlakis/notts-digital/pull/63

**Pull request merged**
