### PR TITLE
Add Notts Dev Workshop item to list

### PR DESCRIPTION
**Pull request by stoiveyp**
I'd like to add a new tech meetup to the list - Notts Dev Workshop. They've had a couple of meetings now and are actively adding new events. Hopefully the change to the request is acceptable. Thanks.

### CODE REVIEW

**Comment by sdh100shaun** [comment]
Looks good - welcome to Nottingham Digital  - thanks for the PR

**Comment by sdh100shaun** [comment]
Could I make a comment - in relation to the content -  would you be adverse to removing this "which the local community is currently saturated with" from your event description? I don't know what other community facilitators feel @andrewseward  @jhigman  @jhuskisson @pavlakis  (for those directly here) - feel but I would suggest it would be fine without that.

**Comment by andrewseward** [comment]
@stoiveyp I have to say I too am pretty uncomfortable with the "saturated" comment, apart from the fact that it misrepresents the content of other meetups, it's also not really in the spirit of what we're trying to achieve as a collaborative, supportive group of organisers.

Let's work together to bring more people into the scene and advance Nottingham's tech community rather than stepping on each other, we will achieve much more.

**Comment by andrewseward** [comment]
(apologies if you didn't actually write that copy @stoiveyp)

**Comment by jhigman** [comment]
Hi @stoiveyp, thanks very much for contributing, sounds like a great meetup. 

Could I just ask that the description here could be kept down to a one-liner? That was the original plan for the site - just a simple strapline for each meetup, and a link to more details? Particularly on mobile, it  keeps it useable..

Thanks very much!

**Comment by stoiveyp** [comment]
Sorry for the delay in replying all - been off of github due to my day job getting in the way. I was adding the copy for someone who organises the meetup - I'll link them to this discussion and handle any alterations.

**Comment by stoiveyp** [comment]
Never mind - seen it's being handled

**Pull request merged**
